services:
  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
